client:
  batch_size: 32
  local_epochs: 1
  learning_rate: 0.001

dataset:
  name: cifar10
  num_clients: 10 # 5
  partition_type: iid
  dirichlet_alpha: 0.5

attack:
  enabled: true
  type: gaussian
  byzantine_ratio: 0.5
  params:
    mean: 0.0
    std: 5.0

system:
  device: cpu
