# configs/server_config_fedavg.yaml

experiment_name: fedavg_with_attack
seed: 42

server:
  strategy: fedavg
  rounds: 50 #5
  min_clients: 10 # 5
  num_clients: 10 # 5

output:
  save_history: true
  save_plot: true
  save_dir: results/
